Remove additionalProperties from intersected objects.
StefanTerdell/zod-to-json-schema pull request #65
Opened 2023-05-09 16:51 UTC by Andy2003

resolves #64

2023-05-09 20:51 UTC, StefanTerdell requested changes

2023-05-09 20:51 UTC, StefanTerdell commented on src/parsers/intersection.ts
> +  return allOf.length ? {allOf, unevaluatedProperties: false} : undefined;
Only set this to false if the conditional on line 25 kicks in. You could instantiate it as undefined beforehand and set it to false in the if-statement, for instance

2023-05-09 20:52 UTC, StefanTerdell commented on src/parsers/intersection.ts
> +  return allOf.length ? {allOf, unevaluatedProperties: false} : undefined;
Actually I guess all of the object schemas should have additionalProperties set to false for this to apply

2023-05-10 08:43 UTC, Andy2003 commented on src/parsers/intersection.ts
> +    ...unevaluatedProperties
@StefanTerdell the `unevaluatedProperties` property was introduced in JsonSchema `2019-09`, but this library is generating `Draft-7`. Should we upgrade to `2019-09` or should I remove this new field?

2023-05-11 17:48 UTC, StefanTerdell approved these changes

2023-05-11 17:49 UTC, merged